   1 : What is Generative AI and what are its primary use cases across industries?


    <-Generative AI refers to a class of artificial intelligence systems designed to create new content—whether text, images, audio, video, or even code—by learning patterns from existing data. Unlike traditional AI, which focuses on classification or prediction, generative AI emphasizes producing outputs that resemble human creativity and originality.

    What Generative AI Is
     Definition: Generative AI uses models like GPT (Generative Pre-trained Transformer), GANs (Generative Adversarial Networks), and VAEs (Variational Autoencoders) to generate realistic and contextually relevant outputs.

     Core Idea: It learns the underlying distribution of data and then samples from it to create new, plausible examples.

       Primary Use Cases Across Industries
       


   2 Explain the role of probabilistic modeling in generative models. How do these models differ from discriminative models?


    <- Generative models aim to capture the joint probability distribution of data. That means they try to learn how features and labels (or words, pixels, etc.) co-occur in the real world.

      Probability Distributions: They model𝑃(𝑥)(the probability of data) or 𝑃(𝑥𝑦)(data and labels together).

     Sampling: Once trained, they can sample from this distribution to generate new, realistic data points
     
     Examples:
      Language models (like GPT) estimate 𝑃(word∣previous words).

    GANs implicitly learn the distribution of images and generate new ones by sampling noise and mapping it to that distribution.
    VAEs explicitly model latent variables with probabilistic assumptions, allowing controlled generation.

     So probabilistic modeling provides the mathematical foundation for why generated outputs look realistic and coherent.

     Difference Between Generative and Discriminative Models
     
     -------------------------------------------------------
   Aspect    Generative Models	    Discriminative Models

Goal	Model the joint distribution 𝑃(𝑥,𝑦)        Model the conditional distribution \( P(y	x) \)

Focus	   Learn how data is generated	     Learn boundaries between classes
Capabilities   Can generate new samples, simulate data	       Can classify or predict labels

Examples	 Naive Bayes, Hidden Markov Models, GANs, VAEs, GPT	     Logistic Regression, SVMs, Random Forests, BERT (for classification)

Strengths	   Useful for unsupervised learning, data augmentation, creative tasks	Often more accurate for classification tasks
Weaknesses	More complex, harder to train	Cannot generate new data

    3: What is the difference between Autoencoders and Variational Autoencoders (VAEs) in the context of text generation?


    <- Mechanism: Encode text into a latent vector → decode back to reconstruct the original.
    Nature: Deterministic. The encoder always produces the same latent representation for the same input.

     Text Generation Limitation:
    They excel at representation learning (e.g., denoising, dimensionality reduction).
    But they don’t naturally generate new text—only reconstruct what was given.
    Sampling new text is difficult because the latent space isn’t explicitly structured for probabilistic variation.

    Variational Autoencoders (VAEs)
    Mechanism: Encoder outputs a distribution (mean + variance) instead of a fixed vector.
    Nature: Probabilistic. A latent vector is sampled from this distribution before decoding.

   Text Generation Advantage:
    Enables diverse outputs—different samples from the same distribution yield different sentences.
    Latent space is smooth and continuous, so nearby points correspond to semantically similar text.
    Much better suited for creative tasks like paraphrasing, dialogue generation, or producing variations of sentences.

     Key Differences in Text Generation
  Feature	    Autoencoder	        Variational Autoencoder
 Latent Space	 Fixed vector	  Distribution (mean + variance)
 Generative Ability	   Limited (reconstruction only)	Strong (can sample new text)
 Output Diversity	    Low	                 High
 Use Cases	Feature extraction, denoising	Text generation, paraphrasing, creative writing



    4: Describe the working of attention mechanisms in Neural Machine Translation (NMT). Why are they critical?

    <-  Traditional sequence-to-sequence models (encoder–decoder with RNNs/LSTMs) struggled with long sentences because the decoder had to rely on a single fixed-length context vector. Attention solved this by letting the decoder “look back” at the entire input sequence dynamically.

     1 Encoder: Processes the source sentence into hidden states (one per word).

     2 Attention Layer:
       At each decoding step, the model computes attention weights over all encoder hidden states.
      These weights indicate how relevant each source word is to the current target word being generated.
     A context vector is formed as a weighted sum of encoder states.
     Decoder: Uses the context vector + its own hidden state to predict the next target word.

     Why Attention Is Critical
     Handles Long Sentences: Instead of compressing everything into one vector, attention allows the model to selectively focus on relevant parts of the input.
     Improves Accuracy: Especially for languages with complex grammar or word order differences.
     Interpretability: Attention weights can be visualized, showing which source words influenced each translation—helpful for debugging and trust.
     Foundation for Transformers: The success of attention in NMT led directly to the Transformer architecture, which relies entirely on self-attention (no RNNs).

   ✨ Example
     Suppose we’re translating “Je t’aime” → “I love you”:
     When generating “I”, attention focuses on “Je”.
     When generating “love”, attention shifts to “t’”.
     When generating “you”, attention highlights “aime”.

     So, attention mechanisms are critical because they enable context-sensitive, accurate, and scalable translations, making modern NMT systems like Transformers (used in Google Translate and GPT-based models) possible.

     Would you like me to also sketch a diagram of the attention workflow (encoder states → attention weights → context vector → decoder)? That visual could make the mechanism even clearer for your assignment.  

  5: What ethical considerations must be addressed when using generative AI for creative content such as poetry or storytelling?



    <-  When using Generative AI for creative content like poetry, storytelling, or art, several ethical considerations must be carefully addressed. These ensure that AI creativity is responsible, fair, and trustworthy:

    Key Ethical Considerations
     1. Authorship & Attribution
     Who owns AI-generated content? Is it the developer, the user, or the AI system?
     Clear attribution is needed to avoid misleading claims about human vs. machine authorship.

     2. Originality vs. Plagiarism
     Generative AI learns from vast datasets, which may include copyrighted works.
     Outputs must be checked to avoid unintentional plagiarism or replication of protected material.

     3. Bias & Representation
       Training data often reflects societal biases (gender, race, culture).
      AI-generated stories or poems may reinforce stereotypes unless carefully monitored.

     4.Cultural Sensitivity
      Creative content can touch on traditions, religions, or identities.
      AI must avoid producing offensive or insensitive material, especially when generating across cultures.

     5.Misinformation & Manipulation
       Storytelling AI could be misused to spread false narratives or propaganda.
       Safeguards are needed to prevent harmful or deceptive outputs.

      6.Emotional Impact
        AI-generated poetry or stories may evoke strong emotions.
       Transparency is important so audiences know when content is machine-created, preventing emotional manipulation.

     7.Creative Labor & Human Artists
      Overuse of AI in creative industries may undervalue human artistry.
     Ethical deployment should balance augmentation (helping artists) vs. replacement (displacing them).

    8 .Consent & Data Use
     If training data includes personal writings, privacy and consent issues arise.
     Datasets must be curated responsibly to respect authors’ rights.


    6: Use the following small text dataset to train a simple Variational Autoencoder (VAE) for text reconstruction:
    ["The sky is blue", "The sun is bright", "The grass is green",  
    "The night is dark", "The stars are shining"]
   1. Preprocess the data (tokenize and pad the sequences).
   2. Build a basic VAE model for text reconstruction.
   3. Train the model and show how it reconstructs or       generates similar sentences.

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Lambda
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K

# Dataset
texts = ["The sky is blue", "The sun is bright", "The grass is green",
         "The night is dark", "The stars are shining"]

# Tokenize
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
word_index = tokenizer.word_index
vocab_size = len(word_index) + 1

# Pad sequences
max_len = max(len(seq) for seq in sequences)
data = pad_sequences(sequences, maxlen=max_len, padding='post')

print("Vocabulary:", word_index)
print("Padded Data:\n", data)


Vocabulary: {'the': 1, 'is': 2, 'sky': 3, 'blue': 4, 'sun': 5, 'bright': 6, 'grass': 7, 'green': 8, 'night': 9, 'dark': 10, 'stars': 11, 'are': 12, 'shining': 13}
Padded Data:
 [[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]


    7: Use a pre-trained GPT model (like GPT-2 or GPT-3) to translate a short English paragraph into French and German. Provide the original and translated text.

   

    <-  enerative AI is transforming industries by enabling machines to create human-like content. It helps in writing, designing, and even storytelling."

    🇫🇷 French Translation
     "L’intelligence artificielle générative transforme les industries en permettant aux machines de créer du contenu semblable à celui des humains. Elle aide à écrire, concevoir et même raconter des histoires."

    🇩🇪 German Translation
     "Generative KI verändert die Branchen, indem sie Maschinen ermöglicht, menschenähnliche Inhalte zu erstellen. Sie hilft beim Schreiben, Gestalten und sogar beim Erzählen von Geschichten."


    8: Implement a simple attention-based encoder-decoder model for English-to-Spanish translation using Tensorflow or PyTorch.



    <-Here’s a clear example of how to implement a simple attention-based encoder–decoder model for English-to-Spanish translation using TensorFlow. This is a toy demonstration (with a tiny dataset), but it shows the mechanics of attention in NMT.\
    

In [15]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tiny dataset
english_sentences = ["hello", "how are you", "good morning", "thank you", "good night"]
spanish_sentences = ["hola", "cómo estás", "buenos días", "gracias", "buenas noches"]

# Tokenize English
eng_tokenizer = Tokenizer()
eng_tokenizer.fit_on_texts(english_sentences)
eng_sequences = eng_tokenizer.texts_to_sequences(english_sentences)
eng_vocab_size = len(eng_tokenizer.word_index) + 1
max_eng_len = max(len(seq) for seq in eng_sequences)
eng_data = pad_sequences(eng_sequences, maxlen=max_eng_len, padding='post')

# Tokenize Spanish
spa_tokenizer = Tokenizer()
spa_tokenizer.fit_on_texts(spanish_sentences)
spa_sequences = spa_tokenizer.texts_to_sequences(spanish_sentences)
spa_vocab_size = len(spa_tokenizer.word_index) + 1
max_spa_len = max(len(seq) for seq in spa_sequences)
spa_data = pad_sequences(spa_sequences, maxlen=max_spa_len, padding='post')


In [16]:
# Encoder
encoder_inputs = tf.keras.layers.Input(shape=(max_eng_len,))
enc_emb = tf.keras.layers.Embedding(eng_vocab_size, 64)(encoder_inputs)
encoder_lstm = tf.keras.layers.LSTM(64, return_sequences=True, return_state=True)
encoder_outputs, state_h, state_c = encoder_lstm(enc_emb)

# Decoder
decoder_inputs = tf.keras.layers.Input(shape=(max_spa_len,))
dec_emb_layer = tf.keras.layers.Embedding(spa_vocab_size, 64)
dec_emb = dec_emb_layer(decoder_inputs)

decoder_lstm = tf.keras.layers.LSTM(64, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(dec_emb, initial_state=[state_h, state_c])

# Attention
score = tf.keras.layers.Dot(axes=[2,2])([decoder_outputs, encoder_outputs])
attention_weights = tf.keras.layers.Activation('softmax')(score)
context = tf.keras.layers.Dot(axes=[2,1])([attention_weights, encoder_outputs])

decoder_combined_context = tf.keras.layers.Concatenate(axis=-1)([context, decoder_outputs])

# Final output
decoder_dense = tf.keras.layers.Dense(spa_vocab_size, activation='softmax')
outputs = decoder_dense(decoder_combined_context)

# Model
model = tf.keras.models.Model([encoder_inputs, decoder_inputs], outputs)
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')


In [17]:
# Shift Spanish sequences for teacher forcing
spa_target = np.expand_dims(spa_data, -1)

model.fit([eng_data, spa_data], spa_target, batch_size=2, epochs=200, verbose=0)


In [18]:
reverse_spa_index = {v:k for k,v in spa_tokenizer.word_index.items()}

def translate(input_text):
    seq = eng_tokenizer.texts_to_sequences([input_text])
    seq = pad_sequences(seq, maxlen=max_eng_len, padding='post')
    pred = model.predict([seq, np.zeros((1,max_spa_len))])
    pred_seq = np.argmax(pred[0], axis=-1)
    return " ".join([reverse_spa_index.get(i,"") for i in pred_seq if i>0])

# Test
for s in english_sentences:
    print(s, "->", translate(s))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 329ms/step
hello -> hola
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
how are you -> cómo estás
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
good morning -> buenos días
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
thank you -> gracias
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
good night -> buenas noches


    9: Use the following short poetry dataset to simulate poem generation with a pre-trained GPT model:
    ["Roses are red, violets are blue,",
    "Sugar is sweet, and so are you.",
    "The moon glows bright in silent skies,",
    "A bird sings where the soft wind sighs."]
    Using this dataset as a reference for poetic structure and language, generate a new 2-4
    line poem using a pre-trained GPT model (such as GPT-2). You may simulate
    fine-tuning by prompting the model with similar poetic patterns.
    Include your code, the prompt used, and the generated poem in your answer.

In [20]:
from transformers import pipeline, set_seed

# Load GPT-2 text generation pipeline
generator = pipeline("text-generation", model="gpt2")
set_seed(42)

# Prompt inspired by dataset
prompt = """Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Now continue the poem:"""

# Generate poem
poem = generator(prompt, max_length=60, num_return_sequences=1)

print("Prompt:\n", prompt)
print("\nGenerated Poem:\n", poem[0]['generated_text'])


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_length', 'num_return_sequences'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=60) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_

Prompt:
 Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Now continue the poem:

Generated Poem:
 Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Now continue the poem:

Now you are ready to know more,

When you will understand and listen to my voice.

The moon glows bright in silent skies,

A bird sings where the soft wind sighs.

Now continue the poem:

Now you are ready to know more,

When you will understand and listen to my voice.

The moon glows bright in silent skies,

A bird sings where the soft wind sighs.

Now continue the poem:

Now you are ready to know more,

When you will understand and listen to my voice.

The moon glows bright in silent skies,

A bird sings where the soft wind sighs.

Now continue the poem:

Now you are ready to know more,

When you will understand and listen to 

    10: Imagine you are building a creative writing assistant for a publishing company. The assistant should generate story plots and character descriptions using Generative AI. Describe how you would design the system, including model selection, training data, bias mitigation, and evaluation methods. Explain the real-world challenges
    you might face.

      <- 1. Model Selection
    Base Models: Use large language models (LLMs) like GPT‑3.5 or GPT‑4 for rich storytelling capabilities.
    Fine‑Tuning: Fine‑tune on curated datasets of story plots, character descriptions, and genre‑specific texts (fantasy, mystery, romance).
    Hybrid Approach: Combine generative models with retrieval‑augmented generation (RAG) so the assistant can reference existing literary databases for inspiration.

       2. Training Data
    Sources: Public domain literature, creative writing prompts, character archetype databases, and user‑generated content with consent.
    Curation: Ensure diversity across cultures, genres, and narrative styles to avoid homogenized outputs.
    Annotation: Label datasets with metadata (tone, genre, character traits) to enable controlled generation.

      3. Bias Mitigation
    Balanced Datasets: Include diverse cultural and demographic representation to avoid stereotypes.
    Filtering: Use bias detection tools to flag problematic outputs (e.g., gender or racial stereotypes in character descriptions).
    Human Review Loop: Editors validate outputs before publication, ensuring sensitivity and originality.

      4. Evaluation Methods
        Automatic Metrics:
        BLEU/ROUGE for linguistic similarity.
        Perplexity for fluency.
     Human Evaluation:
        Creativity, coherence, and emotional impact judged by editors.
      Diversity checks to ensure plots don’t repeat patterns excessively.
   User Feedback:
     Writers rate usefulness of generated plots/characters.
     Iterative improvement based on publishing team input.

     * Real‑World Challenges
    1  Copyright & IP Issues
     Risk of generating text too close to copyrighted works.
     Must ensure outputs are original or sufficiently transformed.

    2 .Bias & Representation
      Models may reinforce stereotypes if training data is skewed.
     Requires ongoing monitoring and dataset refinement.

    3 .Consistency vs. Creativity
     Balancing coherent story arcs with imaginative variety.
     Risk of repetitive tropes if not carefully tuned.

    4.Human–AI Collaboration
     Writers may fear replacement rather than augmentation.
     Need to position the assistant as a creative partner, not a substitute.

    5.Evaluation Complexity
     Creativity is subjective—hard to measure with metrics alone.
     Requires human judgment alongside automated scoring.